-- MySQL Script generated by MySQL Workbench
-- Thu 11 Feb 2016 04:57:00 PM CST
-- Model: TSE Voters MySQL Database    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tsesql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tsesql` ;

-- -----------------------------------------------------
-- Schema tsesql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tsesql` DEFAULT CHARACTER SET utf8 ;
USE `tsesql` ;

-- -----------------------------------------------------
-- Table `tsesql`.`Provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsesql`.`Provinces` (
  `idProvince` TINYINT(1) UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProvince`))
ENGINE = InnoDB
COMMENT = 'Costa Rica has 7 provinces, plus one code for consulates.';


-- -----------------------------------------------------
-- Table `tsesql`.`Cantones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsesql`.`Cantones` (
  `idCanton` TINYINT(2) UNSIGNED NOT NULL,
  `canton` VARCHAR(30) NOT NULL,
  `Provincias_idProvincia` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCanton`, `Provincias_idProvincia`),
  INDEX `fk_Cantones_Provincias_idx` (`Provincias_idProvincia` ASC),
  CONSTRAINT `fk_Cantones_Provincias`
    FOREIGN KEY (`Provincias_idProvincia`)
    REFERENCES `tsesql`.`Provinces` (`idProvince`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'As of 02/2016 Costa Rica has 81 cantons (124 if including consulates).\nThe largest name was \"REPUBLICA DOMINICANA\" (20 characters).';


-- -----------------------------------------------------
-- Table `tsesql`.`Distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsesql`.`Distritos` (
  `idDistrito` INT UNSIGNED NOT NULL,
  `distrito` VARCHAR(45) NOT NULL,
  `Cantones_idCanton` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idDistrito`, `Cantones_idCanton`),
  INDEX `fk_Distritos_Cantones_idx` (`Cantones_idCanton` ASC),
  CONSTRAINT `fk_Distritos_Cantones`
    FOREIGN KEY (`Cantones_idCanton`)
    REFERENCES `tsesql`.`Cantones` (`idCanton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'As of 02/2016 Costa Rica has 2068 districts (2123 if including consulates).\nThe largest name was \"EMPALME ARRIBA GUARIA(PARTE OESTE)\" (34 characters).';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tsesql`.`Provinces`
-- -----------------------------------------------------
START TRANSACTION;
USE `tsesql`;

{% if provinces -%}
INSERT INTO `tsesql`.`Provincias` (`idProvincia`, `provincia`) VALUES
{%- for province_code, name in provinces.items() %}
    ({{province_code}}, '{{name}}')
{%- endfor -%}
;
{%- endif %}

COMMIT;
