-- MySQL Script generated by MySQL Workbench
-- Thu 11 Feb 2016 06:28:25 PM CST
-- Model: TSE Voters MySQL Database    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tsesql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tsesql` ;

-- -----------------------------------------------------
-- Schema tsesql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tsesql` DEFAULT CHARACTER SET utf8 ;
USE `tsesql` ;

-- -----------------------------------------------------
-- Table `tsesql`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsesql`.`province` (
  `id_province` TINYINT(1) UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB
COMMENT = 'Costa Rica has 7 provinces, plus one code for consulates.';


-- -----------------------------------------------------
-- Table `tsesql`.`canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsesql`.`canton` (
  `id_canton` SMALLINT(3) UNSIGNED NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `province_id_province` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_canton`, `province_id_province`),
  INDEX `fk_canton_province1_idx` (`province_id_province` ASC),
  CONSTRAINT `fk_canton_province1`
    FOREIGN KEY (`province_id_province`)
    REFERENCES `tsesql`.`province` (`id_province`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'As of 02/2016 Costa Rica has 81 cantons (124 if including consulates).\nThe largest name was \"REPUBLICA DOMINICANA\" (20 characters).';


-- -----------------------------------------------------
-- Table `tsesql`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsesql`.`district` (
  `id_district` MEDIUMINT(6) UNSIGNED NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `canton_id_canton` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_district`, `canton_id_canton`),
  INDEX `fk_district_canton1_idx` (`canton_id_canton` ASC),
  CONSTRAINT `fk_district_canton1`
    FOREIGN KEY (`canton_id_canton`)
    REFERENCES `tsesql`.`canton` (`id_canton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'As of 02/2016 Costa Rica has 2068 districts (2123 if including consulates).\nThe largest name was \"EMPALME ARRIBA GUARIA(PARTE OESTE)\" (34 characters).';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tsesql`.`province`
-- -----------------------------------------------------
START TRANSACTION;
USE `tsesql`;

{% if provinces -%}
INSERT INTO `tsesql`.`province` (`id_province`, `name`) VALUES
{%- for province_code, name in provinces.items() %}
    ({{province_code}}, '{{name}}'){% if not loop.last %},{% endif %}
{%- endfor -%}
;

COMMIT;
{%- endif %}

-- -----------------------------------------------------
-- Data for table `tsesql`.`canton`
-- -----------------------------------------------------
START TRANSACTION;
USE `tsesql`;

{% if cantons -%}
INSERT INTO `tsesql`.`canton` (`id_canton`, `name`, `province_id_province`)
{%- for (province_code, canton_code), name in cantons.items() %}
    ({{province_code}}{{'{:02d}'.format(canton_code)}}, '{{name}}', {{province_code}}){% if not loop.last %},{% endif %}
{%- endfor -%}
;

COMMIT;
{%- endif %}


-- -----------------------------------------------------
-- Data for table `tsesql`.`district`
-- -----------------------------------------------------
START TRANSACTION;
USE `tsesql`;

{% if districts -%}
INSERT INTO `tsesql`.`district` (`id_district`, `name`, `canton_id_canton`) VALUES
{%- for (province_code, canton_code, district_code), name in districts.items() %}
    ({{province_code}}{{'{:02d}'.format(canton_code)}}{{'{:03d}'.format(district_code)}}, '{{name}}', {{province_code}}{{'{:02d}'.format(canton_code)}}){% if not loop.last %},{% endif %}
{%- endfor -%}
;

COMMIT;
{%- endif %}
